newssite/news/urls.py
from django.conf.urls import url

from . import views as news_views
from django.urls import path,include
from subscription.views import model_view
from polls.views import model_poll_view,model_poll_dyanmic_view
from survey.views import model_survey_view
from rest_framework.urlpatterns import format_suffix_patterns
from restapi import views
from comments.views import model_comment_view, model_get_comment, model_get_child_comment
from ratings.views import ratings_view,average_rating
from sharing.views import share_news
from AdMgmt.views import addmodel_view,click_view
from restapimobile.views import RestView,SortView,SortByPopularity,GetCategoryView,ApiKeyView,CheckApi,TagView,ApiView,NewsIdViews,NewsUpdateViews
from news.views import category_template,home_template
from analytics.views import analytics_view
# from seo_app.views import seo_site_view,site_description_view

from usermgt.views import register, user_login, user_logout ,account, add_post ,apply_as, edit_post, publish_post
from usermgt.dashboard import list_posts, assign_posts, review_posts, preview_post_changes
# from django.contrib.auth.views import login
from django.conf import settings
from django.conf.urls.static import static
from theme.news_import import  get_news

urlpatterns = [
    # url(r"^$", views.home_view, name ="home_page"),
    path('subscription/', model_view),
    path('pollanswer/', model_poll_view),
    path('polldynamic/<int:pid>/', model_poll_dyanmic_view),
    path('survey/', model_survey_view),
    path('account/register/', register),
    path('account/login/',user_login),
    path('account/logout/',user_logout),
    path('account/', account),
    path('account/<str:site>/', account),
    path('account/post/add/<str:site>/', add_post),
    path('account/post/list/', list_posts),
    path('account/post/list/<str:site>/', list_posts),
    path('account/post/assign/<str:slug>/', assign_posts),
    path('account/post/review/<str:slug>/', review_posts),
    path('account/post/edit/<str:slug>/', edit_post),
    path('account/post/publish/<int:postid>/', publish_post),
    path('preview/post/<int:hist_id>/', preview_post_changes),
    path('account/apply/<str:role>/', apply_as),
    # path('rest/',views.List.as_view()),
    path('rest/<int:pid>/',views.ViewList.as_view()),
    path('user/',views.restapi_view),
    path('addcomment/',model_comment_view),
    path('getcomment/',model_get_comment),
    path('getchid_comments/',model_get_child_comment),
    # path('getchilds/',child_view.as_view()),
    path('add_ratings/',ratings_view),
    # path('average/',average_rating),
    path('news_share/',share_news),
    path('news_import/',get_news),
    # path('shared/',referer_view),
    # path('shared/url/',redirect),
    path('advertise/',addmodel_view),
    path('clicks/',click_view),
    path('api/language/getcategories/<str:site>/',RestView.as_view()),
    path('sortbydate/',SortView.as_view()),
    path('sortbypopularity/',SortByPopularity.as_view()),
    path('api/language/gettags/<str:site>/',TagView.as_view()),
    path('api/language/getnews/',GetCategoryView.as_view()),
    path('apikeymodel/',ApiView.as_view()),
    path('addkey/',ApiKeyView),
    path('api/language/getnews/<int:pid>/',NewsIdViews.as_view()),
    path('api/language/news_update/<int:pid>/',NewsUpdateViews.as_view()),

    path('category/',category_template),
    path('',home_template),
    # path('analytics/',analytics_view),
    # path('seo/',seo_site_view),
    # path('seodescription/<str:locale>/',site_description_view),
    # path('analyticspd/',analyticspd),

    path('',include('user_auth.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('p/<str:slug>/', news_views.page_view),
    path('<str:lang>/p/<str:slug>/', news_views.page_view),
    path('<str:slug>/', news_views.slug_view, name ="slug_page"),
    path('<str:lang>/<str:slug>/', news_views.slug_view, name ="slug_page"),

    # static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),

    # url(r"^(?P<slug>[\w]+)/$", news_views.slug_view, name ="slug_page"),
    # path('admin/', admin.site.urls),
    # re_path(r'^files/', include('filer.urls')),


]


urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'html']) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newssite/newssite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
# from django.conf.urls.static import static
from django.urls import include, re_path
from django.views.static import serve


from django.conf.urls import include, url
from news import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('summernote/', include('django_summernote.urls')),
    url(r'^', include("news.urls")),
    # re_path(r'^files/', include('filer.urls')),
    
]

# static files (images, css, javascript, etc.)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
# urlpatterns += re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_URL}),

newssite/polls/models.py
from django.db import models

# Create your models here.
class PollAnswer(models.Model):
    
    answer = models.CharField(max_length=120)
    email = models.EmailField()
    
class Polls(models.Model):
    
    question = models.CharField(max_length=120)
    answer1 = models.TextField()
    answer2 = models.TextField()
    answer3 = models.TextField()
    answer4 = models.TextField()
    StartDate = models.DateField()
    EndDate = models.DateField()

newssite/usermgt/models.py
from django.db import models
from django.contrib.auth.models import User

# from filer.fields.image import FilerImageField

from news.models import DEFINED_SITES
# from multiselectfield import MultiSelectField
# from .roles import UserRoles , UserCapability


# Create your models here.
RoleObj = {
  0:"Subscriber",
  1:"Editor",
  2:"Reviewer",
  3:"Chief Editor",
  4:"Content Manager",
  5:"Site Admin",
  6:"SEO Expert",
  7:"Ad Publisher",
}
Roles =(
    (0, "Subscriber"),
    (1,"Editor"),
    (2,"Reviewer"),
    (3, "Chief Editor"),
    (4, "Content Manager"),
    (5, "Site Admin"),
    (6, "SEO Expert"),
    (7, "Ad Publisher"),
    )
Activity_choice = (
    (0, "Added"),
    (1, "Edited"),
    (2, "Marked ready for review"),
    (3, "Assigned for review"),
    (4, "Reviewed"),
    (5, "Finalised"),
    (6, "Published"),

    )

Activity_choice_DICT = {
    0: "Added",
    1: "Edited",
    2: "Marked ready for review",
    3: "Assigned for review",
    4: "Reviewed",
    5: "Finalised",
    6: "Published",
    }
Item_choice_DICT = {
    'post': "Post",
    'page': "Page",
    'ad': "Ad",
    }

Item_choice = (
    ('post', "Post"),
    ('page', "Page"),
    ('ad', "Ad"),
    )

class UserRoles(models.Model):
  class Meta:
        verbose_name_plural = "User Roles"
        verbose_name = "User Role"
  role = models.CharField(max_length=50, verbose_name = "User Role", unique=True)
  description = models.CharField(max_length=150,blank=True, null=True, verbose_name = "Role description")
  def __str__(self):
      if self.description:
          return self.role +" ("+self.description+")"
      else:
          return self.role

class UserCapability(models.Model):
    class Meta:
          verbose_name_plural = "User Capabilities"
          verbose_name = "User Capability"
    cap = models.CharField(max_length=50, verbose_name = "User Capability", unique=True)
    description = models.CharField(max_length=150, blank=True, null=True,verbose_name = "Capability description")
    def __str__(self):
        if self.description:
            return self.cap +" ("+self.description+")"
        else:
            return self.cap

class RoleCapability(models.Model):
    class Meta:
          verbose_name_plural = "Role Capabilities"
          verbose_name = "Role Capability"
    role = models.OneToOneField(UserRoles, on_delete=models.CASCADE, related_name ='user_role', verbose_name = "Role", unique=True)
    cap = models.ManyToManyField(UserCapability, related_name ='user_role_cap', verbose_name = "Allowed Capability")
    def __str__(self):
        return self.role.role

class NTUser(models.Model):
  class Meta:
        verbose_name_plural = "Users"
        verbose_name = "User"
  karma = models.PositiveIntegerField(default=0)
  bio = models.TextField(max_length=500, blank=True, default="")
  user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name ='user_profile', verbose_name = "User")
  is_reviewed = models.BooleanField(verbose_name = "Profile Reviewed", default=False)
  is_rejected = models.BooleanField(verbose_name = "Profile Rejected", default=False)
  email_varified = models.BooleanField(verbose_name = "Varified Email", default=False)
  accepted = models.BooleanField(verbose_name = "Accepted T&C", default=False)
  country_code = models.CharField(max_length=5, default='np')
  phone = models.CharField(max_length=20, null=True, blank=True, default = "", verbose_name = "Phone number")
  # proof1 = FilerImageField(on_delete=models.CASCADE,null=True, blank=True, default = None,related_name="proof_attachment1", verbose_name = "Citizenship Proof")
  proof1 = models.ImageField(upload_to='aaplications/%Y/%m/%d/',blank=True,null=True,  default = None, verbose_name = "Citizenship Proof")
  # proof2 = FilerImageField(on_delete=models.CASCADE,null=True, blank=True, default = None,related_name="proof_attachment2", verbose_name = "Other Proof")
  proof2 = models.ImageField(upload_to='aaplications/%Y/%m/%d/', blank=True, null=True,  default = None, verbose_name = "Other Proof")
  blog = models.URLField(max_length=200,null=True, blank=True, default = None, verbose_name = "Blog URL")
  twitter = models.CharField(max_length=50,null=True, blank=True, default = None, verbose_name = "Twitter Handle")
  profile_pic = models.ImageField(upload_to='profile/%Y/%m/%d/',blank=True,null=True,  default = None, verbose_name = "User's Image")
  # profile_pic = FilerImageField(on_delete=models.CASCADE,null=True, blank=True, default = None,related_name="profile_attachment", verbose_name = "User's Image")
  # allowed_sites = MultiSelectField(choices=DEFINED_SITES, default = 'en', max_choices=2)
  primary_site = models.CharField(max_length=4, choices =DEFINED_SITES, default = 'en', verbose_name = "Primary site")
  user_type = models.ForeignKey(UserRoles, on_delete=models.CASCADE, default = None,blank=True, null=True,related_name ='nt_user_role', verbose_name = "Primary site role")
  secondary_site = models.CharField(max_length=4, choices =DEFINED_SITES, default = None,blank=True, null=True, verbose_name = "Secondary site")
  secondary_user_type = models.ForeignKey(UserRoles, on_delete=models.CASCADE, default = None,blank=True, null=True,related_name ='nt_user_second_role', verbose_name = "Secondary site role")
  rejection_msg = models.CharField(max_length=200, null=True, blank=True, default = "", verbose_name = "Rejection Message")

  def assign_user_role(self, site, role, strict=False):
      roleobj = UserRoles.objects.filter(role=role).first()
      if not roleobj is None:
          print("assign_user_role {}".format(site))
          return self.add_site_capabilities(site, roleobj, strict)
      else:
          print("{} role not found".format(role))
          return  False

  def getAllowedCapabilities(self,site):
      cap = AllowedCapability.objects.filter(ntuser=self,site=site).first()
      if cap is None:
          return False
      else:
          return cap

  def add_site_capabilities(self, site, role, strict=False):
      print("add_site_capabilities executing {}".format(site))
      cap = RoleCapability.objects.filter(role=role).first()
      print(cap.cap.all())
      allowed_present = self.getAllowedCapabilities(site)
      if allowed_present is False:
          allowed = AllowedCapability()
          allowed.ntuser= self
          allowed.site = site
          allowed.save()
          allowed.cap.set(cap.cap.all())
          allowed.save()
          return True
      else:
          if strict:
              for c in allowed_present.cap.all():
                  allowed_present.cap.remove(c)

          for c in cap.cap.all():
              if allowed_present.cap.filter(cap=c).first() is None:
                  allowed_present.cap.add(c)
                  # allowed_present.cap.save()
          allowed_present.save()
          return True

  def assign_subscriber_role(self):
      for site in DEFINED_SITES:
          print("Assigning to site {}".format(site[0]))
          self.assign_user_role(site[0], "Subscriber")



  def save(self,*args, **kwargs):
      if self.primary_site and self.user_type:
          self.add_site_capabilities(self.primary_site,  self.user_type, strict=True)

      if self.secondary_site and self.secondary_user_type:
          self.add_site_capabilities(self.secondary_site,  self.secondary_user_type, strict=True)

      super(NTUser, self).save(*args, **kwargs)

  def __str__(self):
        return self.user.get_full_name() or self.user.username

class Activity(models.Model):
  class Meta:
        verbose_name_plural = "Activities"
        verbose_name = "Activity"

  ntuser = models.ForeignKey(NTUser, on_delete=models.CASCADE, related_name ='nt_user', verbose_name = "User")
  activity_type = models.PositiveIntegerField(choices=Activity_choice, default=0)
  item_type = models.CharField(max_length=10,choices=Item_choice, default="Item type")
  item_id = models.PositiveIntegerField(default=0)
  history_id = models.PositiveIntegerField(default=0)
  date = models.DateTimeField(auto_now=True, verbose_name = "Activity Date")
  comment = models.TextField(blank=True, null=True, verbose_name = "Comment")
  finalise = models.BooleanField(verbose_name = "Finalised", default=False)

  def __str__(self):
      return self.ntuser.user.get_full_name() + " " + Activity_choice_DICT[self.activity_type] + " " +Item_choice_DICT[self.item_type]


class AllowedCapability(models.Model):
    class Meta:
          verbose_name_plural = "Allowed Capabilities"
          verbose_name = "Allowed Capability"
          unique_together = [['ntuser', 'site']]

    ntuser = models.ForeignKey(NTUser, on_delete=models.CASCADE, related_name ='nt_cap_user', verbose_name = "User")
    cap = models.ManyToManyField(UserCapability, related_name ='nt_user_capabilities', verbose_name = "Allowed Capability")
    site = models.CharField(max_length=4, choices =DEFINED_SITES, default = 'en')

newssite/templates/usermgt/user-404.html
the page you are looking for doesnt exists

newssite/templates/usermgt/user-apply-not-applicable.html
Not applicable!

newssite/templates/usermgt/user-apply.html
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if applied %}
        <h1>Thank you for Applying!</h1>
      {% else %}
        <h1>Apply as {{ role }}</h1>
        <h3>Just fill out the form.</h3>
<form method="POST" enctype="multipart/form-data" >
    
    <div class="field">
        {{ userform.country_code.errors }}
        <label for="id_first_name">Country Code: </label>
        {{ userform.country_code }}
    </div>
    <div class="field">
        {{ userform.proof1.errors }}
        <label for="id_citizenship">Citizenship: </label>
        {{ userform.proof1 }}
    </div>
    <div class="field">
        {{ userform.proof2.errors }}
        <label for="id_proof2">Other Proof: </label>
        {{ userform.proof2 }}
    </div>
    <div class="field">
        {{ userform.blog.errors }}
        <label for="id_username">Blog link: </label>
        {{ userform.blog }}
    </div>
    <div class="field">
        {{ userform.twitter.errors }}
        <label for="id_twitter">Twitter Handle: </label>
        {{ userform.twitter }}
    </div>
    <div class="field">
        {{ userform.profile_pic.errors }}
        <label for="id_profile_pic">Profile pic: </label>
        {{ userform.profile_pic }}
    </div>
    
    <div class="field">
        {{ userform.bio.errors }}
        <label for="id_bio">User bio: </label>
        {{ userform.bio }}
    </div>
    
    
    {{ userform.user_type }}
    
    {% csrf_token %}

  <input type="submit" name="" value="Apply">

</form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

newssite/templates/usermgt/user-edit-post.html
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if submitted %}
        <h1>Thank you for Editing!</h1>
      {% else %}
        <h1>Edit post</h1>
        
        
<form method="POST" enctype="multipart/form-data">
    {{ postform.media }}
    {{ postform.as_p }}
    {% csrf_token %}
    
     <!--
    {% if postform.tag %}
    <div class="field">
        {{ postform.tag.errors }}
      <label for="id_post_tag">News Tags: </label>
      {% for radio in postform.tag %}
          <label for="{{ radio.id_for_label }}">
              {{ radio.choice_label }}
              <span class="radio">{{ radio.tag }}</span>
          </label>
      {% endfor %}
    </div>
      {% endif %}
    
     {% if postform.category %}
     <label for="id_profile_pic">News category: </label>
    {% for radio in postform.category %}
    
    
      <label for="{{ radio.id_for_label }}">
          {{ radio.choice_label }}
          <span class="radio">{{ radio.tag }}</span>
      </label>
    {% endfor %}
      {% endif %}
    -->
    
    <input type="submit" value="Save Draft"/>
</form>

  {% endif %}
    </div>
  </div>
{% endblock %}

newssite/templates/usermgt/user-login.html
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      
        <h1>Login Here</h1>
        <h3>Just fill out the form.</h3>
<form method="POST">

    <div class="field">
        {{ form.username.errors }}
        <label for="id_first_name">Username: </label>
        {{ form.username }}
    </div>
    <div class="field">
        {{ form.password.errors }}
        <label for="id_last_name">Password: </label>
        {{ form.password }}
    </div>
    
    {% csrf_token %}
  <input type="submit" class="logBut" value="Log in"/>
</form>
    </div>
  </div>
{% endblock %}

newssite/templates/usermgt/user-not-permitted.html
Sorry You havent been given authority to {{ action }}!
Please contact content administrator.

newssite/templates/usermgt/user-register.html
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form method="POST">
    
    <div class="field">
        {{ userform.first_name.errors }}
        <label for="id_first_name">First name: </label>
        {{ userform.first_name }}
    </div>
    <div class="field">
        {{ userform.last_name.errors }}
        <label for="id_last_name">Last name: </label>
        {{ userform.last_name }}
    </div>
    <div class="field">
        {{ userform.email.errors }}
        <label for="id_email">Email: </label>
        {{ userform.email }}
    </div>
    <div class="field">
        {{ userform.username.errors }}
        <label for="id_username">Username: </label>
        {{ userform.username }}
    </div>
    <div class="field">
        {{ userform.password.errors }}
        <label for="id_password1">Password: </label>
        {{ userform.password }}
    </div>
    {% csrf_token %}
  <input type="submit" name="" value="Register">
</form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

newssite/templates/usermgt/user-rejected.html
Hello {{ user }}! We are sorry to inform your application for role {{ role }} has been rejected.
Here is what reviewers have to say about the reason.

{{ message }}

newssite/templates/usermgt/user-submit-post.html
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if submitted %}
        <h1>Thank you for Submitting!</h1>
      {% else %}
        <h1>Add a post</h1>
        
        
<form method="POST" enctype="multipart/form-data">
    {{ postform.media }}
    {{ postform.as_p }}
    {% csrf_token %}
    
     <!--
    {% if postform.tag %}
    <div class="field">
        {{ postform.tag.errors }}
      <label for="id_post_tag">News Tags: </label>
      {% for radio in postform.tag %}
          <label for="{{ radio.id_for_label }}">
              {{ radio.choice_label }}
              <span class="radio">{{ radio.tag }}</span>
          </label>
      {% endfor %}
    </div>
      {% endif %}
    
     {% if postform.category %}
     <label for="id_profile_pic">News category: </label>
    {% for radio in postform.category %}
    
    
      <label for="{{ radio.id_for_label }}">
          {{ radio.choice_label }}
          <span class="radio">{{ radio.tag }}</span>
      </label>
    {% endfor %}
      {% endif %}
    -->
    
    <input type="submit" value="Submit"/>
</form>

  {% endif %}
    </div>
  </div>
{% endblock %}

newssite/templates/usermgt/user-under-review.html
Hello {{ user }}! We are processing your application for role {{ role }}. Please be patient.
Thank you!